@startuml Chess

	class Chess
	class Turn
	class Player
	class Board
	class Square

	class Coordinate
	class Letter
	class Number

	class Piece
	class Pawn
	class Rook
	class Knight
	class Bishop
	class Queen
	class King

	class Color
	class White
	class Black
	class Movement



	Chess *--> Turn
	Chess *--> Board
	Chess *--> "2" Player

	Turn *--> "2" Player

	Board o--> "32" Piece
	Board *--> "8*8" Square
	Square *--> Coordinate

	Coordinate *--> Letter
	Coordinate *-->Number

	Player ..> "1..*" Movement
	Player *--> Color
	Player o--> Piece
	Player *-- King
	Player *-- Queen
	Player *-- "2" Bishop
	Player *-- "2" Knight
	Player *-- "2" Rook
	Player *-- "8" Pawn

  	Player *-- Goal
	Goal ..> toOpponentSquare
	Goal ..> King

	Color <|-- White
	Color <|-- Black

	Piece <|-- Pawn
	Piece <|-- Bishop
	Piece <|-- Knight
	Piece <|-- Rook
	Piece <|-- Queen
	Piece <|-- King
	Piece *--> InitialPosition
    Piece *-- "0..*" Movement

	Destination <|-- toFreeSquare
	Destination <|-- toOpponentSquare
	Destination *--> Coordinate

	Direction *--> InitialPosition
	Direction *--> Destination

	InitialPosition *--> Coordinate

	Movement *--> Direction
	Movement *--> Quantity

	Direction <|-- Horizontal
	Direction <|-- Vertical
	Direction <|-- Diagonal
	Direction <|-- L

	Quantity <|-- One
	Quantity <|-- Many
@enduml
